// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 5);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1719078378);
user_pref("app.update.lastUpdateTime.region-update-timer", 1719078378);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1719078378);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1718457520);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1719078378);
user_pref("browser.region.update.updated", 1718186489);
user_pref("browser.search.region", "KE");
user_pref("calendar.caldav.googleResync", 1718186486);
user_pref("calendar.list.sortOrder", "c3785dbd-aeed-497a-9d61-098caed3e1d4");
user_pref("calendar.registry.c3785dbd-aeed-497a-9d61-098caed3e1d4.calendar-main-default", true);
user_pref("calendar.registry.c3785dbd-aeed-497a-9d61-098caed3e1d4.calendar-main-in-composite", true);
user_pref("calendar.registry.c3785dbd-aeed-497a-9d61-098caed3e1d4.disabled", true);
user_pref("calendar.registry.c3785dbd-aeed-497a-9d61-098caed3e1d4.name", "Home");
user_pref("calendar.registry.c3785dbd-aeed-497a-9d61-098caed3e1d4.type", "storage");
user_pref("calendar.registry.c3785dbd-aeed-497a-9d61-098caed3e1d4.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Nairobi");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1718457471374");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1719078378);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240513132046");
user_pref("extensions.lastAppVersion", "115.11.0");
user_pref("extensions.lastPlatformVersion", "115.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"b38a8463-e81f-4542-95e1-27d04e5a8ed1\",\"google@search.mozilla.org\":\"61a27dad-e495-4878-a431-062e3b7bbe22\",\"ddg@search.mozilla.org\":\"46428049-86c0-46ea-af99-c663bfd1e175\",\"amazondotcom@search.mozilla.org\":\"6d1b4c9b-b2dc-4b33-a021-7f38b78022b7\",\"wikipedia@search.mozilla.org\":\"bca76bd1-b90d-4ea2-a57e-8e9ba3dbc1fa\",\"bing@search.mozilla.org\":\"3d22f87d-7a61-4ca7-a95a-10b31c12cc6c\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1719081039);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "44729c3f-33f9-434f-b940-60f6490b0ef");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1719081039);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -12632);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1719091024);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1719091024);
user_pref("services.settings.thunderbird.search-config.last_check", 1719091024);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1719091024);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1719081039);
user_pref("toolkit.startup.last_success", 1719078346);
user_pref("toolkit.telemetry.cachedClientID", "a61012ed-c1c7-4294-b0b1-e0b040c6fe26");
user_pref("toolkit.telemetry.previousBuildID", "20240513132046");
